version: 2

models:
  - name: cc_sales_products
    columns:
      ### PK ###
      - name: product_id
        tests:
          - unique
      - name: product_id
        tests:
          - not_null 
      - name: qty_91
        tests:
          - not_null
      - name: avg_daily_qty_91
        tests:
          - not_null